---
- name: Playbook to intall genric tools
  hosts: test
  gather_facts: yes
  become: yes
  become_user: yes
  #vars:
  #  TFROM: 1.8.5
  tasks:
    - name: Check the hostname
      shell: cat /etc/lsb-release
    - name: perform yum update
      shell: yum update
    - name: install tools
      shell: yum install -y unzip jq stress net-tools 